plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ricchary.cotizaciones'
    compileSdk 34

    defaultConfig {
        applicationId 'com.ricchary.cotizaciones'
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    signingConfigs {
        release {
            storeFile file(System.getenv("KEYSTORE_PATH") ?: "../android.keystore")
            storePassword System.getenv("KEYSTORE_PASSWORD") ?: "android123"
            keyAlias System.getenv("KEY_ALIAS") ?: "ricchary"
            keyPassword System.getenv("KEY_PASSWORD") ?: "android123"
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.5.0'
}
